version: '3'
services:
  client: 
    image: grpcweb-devtools-example/client
    ports:
      - "8080:8080"
      
  server:
    image: grpcweb-devtools-example/server
    depends_on:
      - envoy

  envoy:
    image: envoyproxy/envoy:v1.20-latest
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - "8080"
      - "9901"
    ports:
      - "18080:8080"
